// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w1_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a0_x1_w1_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w0_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_ar1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_iid_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x0_w0_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w0_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w1_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w1_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a0_x1_w1_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a0_x1_w1_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x0_w0_no_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w0_no_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_dr_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_ln_iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_ar1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_ar1_mod, 0},
    {"_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bscm_a1_x1_w1_no_iid_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bscm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
