// Generated by rstantools.  Do not edit by hand.

/*
    bscm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bscm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bscm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.38.0-11-g1deff3e
#include <stan/model/model_header.hpp>
namespace model_scm_no_icpt_no_x_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 47> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 16, column 2 to column 24)",
  " (in 'string', line 17, column 2 to column 33)",
  " (in 'string', line 21, column 2 to column 47)",
  " (in 'string', line 22, column 2 to column 39)",
  " (in 'string', line 30, column 2 to column 71)",
  " (in 'string', line 31, column 2 to column 37)",
  " (in 'string', line 32, column 2 to column 50)",
  " (in 'string', line 33, column 2 to column 55)",
  " (in 'string', line 34, column 2 to column 95)",
  " (in 'string', line 35, column 2 to column 89)",
  " (in 'string', line 36, column 2 to column 52)",
  " (in 'string', line 37, column 2 to column 57)",
  " (in 'string', line 38, column 2 to column 41)",
  " (in 'string', line 39, column 2 to column 50)",
  " (in 'string', line 40, column 2 to column 14)",
  " (in 'string', line 46, column 2 to column 24)",
  " (in 'string', line 42, column 4 to column 33)",
  " (in 'string', line 43, column 4 to column 44)",
  " (in 'string', line 44, column 4 to column 39)",
  " (in 'string', line 41, column 2 to line 45, column 3)",
  " (in 'string', line 48, column 4 to column 62)",
  " (in 'string', line 47, column 21 to line 49, column 3)",
  " (in 'string', line 47, column 2 to line 49, column 3)",
  " (in 'string', line 25, column 2 to column 37)",
  " (in 'string', line 26, column 2 to column 30)",
  " (in 'string', line 27, column 2 to column 54)",
  " (in 'string', line 3, column 2 to column 17)",
  " (in 'string', line 4, column 2 to column 21)",
  " (in 'string', line 5, column 2 to column 17)",
  " (in 'string', line 6, column 9 to column 10)",
  " (in 'string', line 6, column 2 to column 14)",
  " (in 'string', line 7, column 9 to column 10)",
  " (in 'string', line 7, column 12 to column 13)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 2 to column 21)",
  " (in 'string', line 9, column 2 to column 24)",
  " (in 'string', line 13, column 9 to column 18)",
  " (in 'string', line 13, column 2 to column 67)",
  " (in 'string', line 17, column 20 to column 21)",
  " (in 'string', line 21, column 9 to column 10)",
  " (in 'string', line 22, column 9 to column 10)",
  " (in 'string', line 30, column 9 to column 10)",
  " (in 'string', line 31, column 9 to column 10)",
  " (in 'string', line 34, column 9 to column 18)",
  " (in 'string', line 35, column 9 to column 18)",
  " (in 'string', line 46, column 9 to column 14)"};
#include <stan_meta_header.hpp>
class model_scm_no_icpt_no_x final : public model_base_crtp<model_scm_no_icpt_no_x> {
private:
  int T;
  int T_pre;
  int J;
  Eigen::Matrix<double,-1,1> y_data__;
  Eigen::Matrix<double,-1,-1> Z_data__;
  double pr_rate_sigma;
  double kappa;
  Eigen::Matrix<double,-1,1> tt_data__;
  int avg_effect_post_cumulative_1dim__;
  int relative_change_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> tt{nullptr, 0};
public:
  ~model_scm_no_icpt_no_x() {}
  model_scm_no_icpt_no_x(stan::io::var_context& context__, unsigned int
                         random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_scm_no_icpt_no_x_namespace::model_scm_no_icpt_no_x";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 27;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 27;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "T_pre", "int",
        std::vector<size_t>{});
      T_pre = std::numeric_limits<int>::min();
      current_statement__ = 28;
      T_pre = context__.vals_i("T_pre")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "T_pre", T_pre, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 29;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("y", "T", T);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(T,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), T);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 31;
        y_flat__ = context__.vals_r("y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("Z", "T", T);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("Z", "J", J);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "Z", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(J)});
      Z_data__ = Eigen::Matrix<double,-1,-1>::Constant(T, J,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Z) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z_data__.data(), T, J);
      {
        std::vector<local_scalar_t__> Z_flat__;
        current_statement__ = 34;
        Z_flat__ = context__.vals_r("Z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            stan::model::assign(Z, Z_flat__[(pos__ - 1)],
              "assigning variable Z", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 35;
      context__.validate_dims("data initialization", "pr_rate_sigma",
        "double", std::vector<size_t>{});
      pr_rate_sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 35;
      pr_rate_sigma = context__.vals_r("pr_rate_sigma")[(1 - 1)];
      current_statement__ = 36;
      context__.validate_dims("data initialization", "kappa", "double",
        std::vector<size_t>{});
      kappa = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 36;
      kappa = context__.vals_r("kappa")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "kappa", kappa, 0);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("tt", "T - T_pre", (T - T_pre));
      current_statement__ = 38;
      tt_data__ = Eigen::Matrix<double,-1,1>::Constant((T - T_pre),
                    std::numeric_limits<double>::quiet_NaN());
      new (&tt) Eigen::Map<Eigen::Matrix<double,-1,1>>(tt_data__.data(), (T -
        T_pre));
      current_statement__ = 38;
      stan::model::assign(tt,
        stan::math::linspaced_vector((T - T_pre), static_cast<double>(1),
          static_cast<double>((T - T_pre))), "assigning variable tt");
      current_statement__ = 39;
      stan::math::validate_non_negative_index("omega_raw", "J", J);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("omega", "J", J);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("synthetic_mean", "T", T);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("synthetic_y", "T", T);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("effect", "T", T);
      current_statement__ = 44;
      avg_effect_post_cumulative_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 44;
      avg_effect_post_cumulative_1dim__ = (T - T_pre);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("avg_effect_post_cumulative",
        "T - T_pre", avg_effect_post_cumulative_1dim__);
      current_statement__ = 45;
      relative_change_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 45;
      relative_change_1dim__ = (T - T_pre);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("relative_change", "T - T_pre",
        relative_change_1dim__);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("log_lik", "T_pre", T_pre);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + J;
  }
  inline std::string model_name() const final {
    return "model_scm_no_icpt_no_x";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.38.0-11-g1deff3e",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_scm_no_icpt_no_x_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto omega_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,1> omega =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(omega,
        stan::math::divide(omega_raw, stan::math::sum(omega_raw)),
        "assigning variable omega");
      Eigen::Matrix<local_scalar_t__,-1,1> synthetic_mean =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(synthetic_mean, stan::math::multiply(Z, omega),
        "assigning variable synthetic_mean");
      {
        current_statement__ = 24;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma,
                         pr_rate_sigma));
        current_statement__ = 25;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(omega_raw, kappa,
                         static_cast<double>(1)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::model::rvalue(y, "y",
                           stan::model::index_min_max(1, T_pre)),
                         stan::model::rvalue(synthetic_mean,
                           "synthetic_mean",
                           stan::model::index_min_max(1, T_pre)), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_scm_no_icpt_no_x_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto omega_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,1> omega =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(omega,
        stan::math::divide(omega_raw, stan::math::sum(omega_raw)),
        "assigning variable omega");
      Eigen::Matrix<local_scalar_t__,-1,1> synthetic_mean =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(synthetic_mean, stan::math::multiply(Z, omega),
        "assigning variable synthetic_mean");
      {
        current_statement__ = 24;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma,
                         pr_rate_sigma));
        current_statement__ = 25;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(omega_raw, kappa,
                         static_cast<double>(1)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::model::rvalue(y, "y",
                           stan::model::index_min_max(1, T_pre)),
                         stan::model::rvalue(synthetic_mean,
                           "synthetic_mean",
                           stan::model::index_min_max(1, T_pre)), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_scm_no_icpt_no_x_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 2;
      auto omega_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      Eigen::Matrix<double,-1,1> omega =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> synthetic_mean =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(sigma);
      out__.write(omega_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      stan::model::assign(omega,
        stan::math::divide(omega_raw, stan::math::sum(omega_raw)),
        "assigning variable omega");
      current_statement__ = 4;
      stan::model::assign(synthetic_mean, stan::math::multiply(Z, omega),
        "assigning variable synthetic_mean");
      if (emit_transformed_parameters__) {
        out__.write(omega);
        out__.write(synthetic_mean);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> synthetic_y =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      stan::model::assign(synthetic_y,
        stan::math::to_vector(
          stan::math::normal_rng(synthetic_mean, sigma, base_rng__)),
        "assigning variable synthetic_y");
      Eigen::Matrix<double,-1,1> effect =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      stan::model::assign(effect, stan::math::subtract(y, synthetic_y),
        "assigning variable effect");
      double avg_effect_pre = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      avg_effect_pre = stan::math::mean(stan::math::head(effect, T_pre));
      double avg_effect_post = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      avg_effect_post = stan::math::mean(
                          stan::math::tail(effect, (T - T_pre)));
      Eigen::Matrix<double,-1,1> avg_effect_post_cumulative =
        Eigen::Matrix<double,-1,1>::Constant(avg_effect_post_cumulative_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      stan::model::assign(avg_effect_post_cumulative,
        stan::math::elt_divide(
          stan::math::cumulative_sum(stan::math::tail(effect, (T - T_pre))),
          tt), "assigning variable avg_effect_post_cumulative");
      Eigen::Matrix<double,-1,1> relative_change =
        Eigen::Matrix<double,-1,1>::Constant(relative_change_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      stan::model::assign(relative_change,
        stan::math::elt_divide(stan::math::tail(synthetic_y, (T - T_pre)),
          stan::model::rvalue(synthetic_y, "synthetic_y",
            stan::model::index_uni(T_pre))),
        "assigning variable relative_change");
      double RMSE_pre = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      RMSE_pre = stan::math::sqrt(
                   stan::math::mean(
                     stan::math::pow(stan::math::head(effect, T_pre), 2)));
      double RMSE_post = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      RMSE_post = stan::math::sqrt(
                    stan::math::mean(
                      stan::math::pow(stan::math::tail(effect, (T - T_pre)),
                        2)));
      double RMSE_ratio = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      RMSE_ratio = (RMSE_post / RMSE_pre);
      double effective_donors = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      effective_donors = stan::math::inv(
                           stan::math::sum(stan::math::square(omega)));
      double R2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 15;
      R2 = static_cast<double>(0);
      {
        double var_res = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 17;
        var_res = stan::math::square(sigma);
        double var_fit = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 18;
        var_fit = stan::math::variance(synthetic_mean);
        current_statement__ = 19;
        R2 = (var_fit / (var_fit + var_res));
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(T_pre,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 23;
      for (int t = 1; t <= T_pre; ++t) {
        current_statement__ = 21;
        stan::model::assign(log_lik,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(t)),
            stan::model::rvalue(synthetic_mean, "synthetic_mean",
              stan::model::index_uni(t)), sigma),
          "assigning variable log_lik", stan::model::index_uni(t));
      }
      out__.write(synthetic_y);
      out__.write(effect);
      out__.write(avg_effect_pre);
      out__.write(avg_effect_post);
      out__.write(avg_effect_post_cumulative);
      out__.write(relative_change);
      out__.write(RMSE_pre);
      out__.write(RMSE_post);
      out__.write(RMSE_ratio);
      out__.write(effective_donors);
      out__.write(R2);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 1;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> omega_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(omega_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable omega_raw");
      out__.write_free_lb(0, omega_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "omega_raw",
        "double", std::vector<size_t>{static_cast<size_t>(J)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 1;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> omega_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> omega_raw_flat__;
        current_statement__ = 2;
        omega_raw_flat__ = context__.vals_r("omega_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          stan::model::assign(omega_raw, omega_raw_flat__[(pos__ - 1)],
            "assigning variable omega_raw", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, omega_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"sigma", "omega_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"omega", "synthetic_mean"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"synthetic_y", "effect", "avg_effect_pre", "avg_effect_post",
             "avg_effect_post_cumulative", "relative_change", "RMSE_pre",
             "RMSE_post", "RMSE_ratio", "effective_donors", "R2", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(J)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J)},
             std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(
                                   avg_effect_post_cumulative_1dim__)},
             std::vector<size_t>{static_cast<size_t>(relative_change_1dim__)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(T_pre)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "sigma");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "omega" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "synthetic_mean" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "synthetic_y" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "effect" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "avg_effect_pre");
      param_names__.emplace_back(std::string() + "avg_effect_post");
      for (int sym1__ = 1; sym1__ <=
           avg_effect_post_cumulative_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() +
          "avg_effect_post_cumulative" + '.' + std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= relative_change_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "relative_change" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "RMSE_pre");
      param_names__.emplace_back(std::string() + "RMSE_post");
      param_names__.emplace_back(std::string() + "RMSE_ratio");
      param_names__.emplace_back(std::string() + "effective_donors");
      param_names__.emplace_back(std::string() + "R2");
      for (int sym1__ = 1; sym1__ <= T_pre; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "sigma");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "omega_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "omega" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "synthetic_mean" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "synthetic_y" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "effect" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "avg_effect_pre");
      param_names__.emplace_back(std::string() + "avg_effect_post");
      for (int sym1__ = 1; sym1__ <=
           avg_effect_post_cumulative_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() +
          "avg_effect_post_cumulative" + '.' + std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= relative_change_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "relative_change" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "RMSE_pre");
      param_names__.emplace_back(std::string() + "RMSE_post");
      param_names__.emplace_back(std::string() + "RMSE_ratio");
      param_names__.emplace_back(std::string() + "effective_donors");
      param_names__.emplace_back(std::string() + "R2");
      for (int sym1__ = 1; sym1__ <= T_pre; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"omega_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"omega\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"synthetic_mean\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"synthetic_y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"effect\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_pre\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_post\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_post_cumulative\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(avg_effect_post_cumulative_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"relative_change\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(relative_change_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_pre\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_post\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_ratio\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"effective_donors\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"R2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_pre) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"omega_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"omega\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"synthetic_mean\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"synthetic_y\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"effect\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_pre\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_post\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"avg_effect_post_cumulative\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(avg_effect_post_cumulative_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"relative_change\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(relative_change_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_pre\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_post\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"RMSE_ratio\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"effective_donors\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"R2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_pre) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + J;
    const size_t num_transformed = emit_transformed_parameters * (J + T);
    const size_t num_gen_quantities = emit_generated_quantities * (T + T + 1
      + 1 + avg_effect_post_cumulative_1dim__ + relative_change_1dim__ + 1 +
      1 + 1 + 1 + 1 + T_pre);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + J;
    const size_t num_transformed = emit_transformed_parameters * (J + T);
    const size_t num_gen_quantities = emit_generated_quantities * (T + T + 1
      + 1 + avg_effect_post_cumulative_1dim__ + relative_change_1dim__ + 1 +
      1 + 1 + 1 + 1 + T_pre);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_scm_no_icpt_no_x_namespace::model_scm_no_icpt_no_x;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_scm_no_icpt_no_x_namespace::profiles__;
}
#endif
#endif
